## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
dist: xenial
julia:
  - 1.0
notifications:
  email: false

script:
  - git clone --branch=feature/binarybuilder https://github.com/JuliaRobotics/AprilTags.jl.git ~/jl/AprilTags.jl
  - cmake -DCMAKE_INSTALL_PREFIX=~/jl/AprilTags.jl/deps/usr
  - make install
  - ls ~/jl/AprilTags.jl/deps -al
  - julia -e 'using Pkg; cd(homedir()*"/jl/AprilTags.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(), Pkg.build("AprilTags"); Pkg.test("AprilTags")'
