## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: xenial
julia:
  - 1.0
notifications:
  email: false

script:
  - julia --color=yes -e 'using Pkg; Pkg.develop(PackageSpec("AprilTags", rev="feature/binarybuilder"))'
  - ls -al
  # - cmake -DCMAKE_INSTALL_PREFIX=~/.julia/dev/AprilTags/deps
